import { hash } from "bcryptjs";

import { db } from "@/lib/db";
import { siteContent } from "@/data/site-content";

function serializeList(items: string[]) {
  return items.join("\n");
}

function serializeGoals(items: Array<{ title: string; description: string }>) {
  return items.map((item) => `${item.title}::${item.description}`).join("\n");
}

async function main() {
  const en = siteContent.en;
  const ar = siteContent.ar;
  const existingAdminCount = await db.adminUser.count();

  if (existingAdminCount === 0) {
    await db.adminUser.create({
      data: {
        email: "admin@example.com",
        name: "Admin",
        passwordHash: await hash("change_me_securely", 12),
      },
    });
  }

  await db.siteSettings.upsert({
    where: { id: "site-settings" },
    update: {},
    create: {
      id: "site-settings",
      projectNameEn: en.siteName,
      projectNameAr: ar.siteName,
      navHomeEn: en.nav[0].label,
      navHomeAr: ar.nav[0].label,
      navAboutEn: en.nav[1].label,
      navAboutAr: ar.nav[1].label,
      navProgramsEn: en.nav[2].label,
      navProgramsAr: ar.nav[2].label,
      navProjectsEn: en.nav[3].label,
      navProjectsAr: ar.nav[3].label,
      navEventsEn: en.nav[4].label,
      navEventsAr: ar.nav[4].label,
      navDonateEn: en.nav[5].label,
      navDonateAr: ar.nav[5].label,
      navContactEn: en.nav[6].label,
      navContactAr: ar.nav[6].label,
      footerDescriptionEn: en.footer.description,
      footerDescriptionAr: ar.footer.description,
      footerContactLabelEn: en.footer.contactLabel,
      footerContactLabelAr: ar.footer.contactLabel,
      footerSocialLabelEn: en.footer.socialLabel,
      footerSocialLabelAr: ar.footer.socialLabel,
      footerDonateLabelEn: en.footer.donateLabel,
      footerDonateLabelAr: ar.footer.donateLabel,
      footerRightsEn: en.footer.rights,
      footerRightsAr: ar.footer.rights,
      socialOneLabelEn: en.footer.socialLinks[0].label,
      socialOneLabelAr: ar.footer.socialLinks[0].label,
      socialOneUrl: en.footer.socialLinks[0].href,
      socialTwoLabelEn: en.footer.socialLinks[1].label,
      socialTwoLabelAr: ar.footer.socialLinks[1].label,
      socialTwoUrl: en.footer.socialLinks[1].href,
      socialThreeLabelEn: en.footer.socialLinks[2].label,
      socialThreeLabelAr: ar.footer.socialLinks[2].label,
      socialThreeUrl: en.footer.socialLinks[2].href,
      seoTitleEn: en.siteName,
      seoTitleAr: ar.siteName,
      seoDescriptionEn: en.footer.description,
      seoDescriptionAr: ar.footer.description,
    },
  });

  await db.homePage.upsert({
    where: { id: "home-page" },
    update: {},
    create: {
      id: "home-page",
      heroEyebrowEn: en.home.hero.eyebrow,
      heroEyebrowAr: ar.home.hero.eyebrow,
      heroTitleEn: en.home.hero.title,
      heroTitleAr: ar.home.hero.title,
      heroDescriptionEn: en.home.hero.description,
      heroDescriptionAr: ar.home.hero.description,
      heroPrimaryActionEn: en.home.hero.primaryAction,
      heroPrimaryActionAr: ar.home.hero.primaryAction,
      heroSecondaryActionEn: en.home.hero.secondaryAction,
      heroSecondaryActionAr: ar.home.hero.secondaryAction,
      heroImageUrl: en.home.hero.image,
      heroImageAltEn: en.home.hero.imageAlt,
      heroImageAltAr: ar.home.hero.imageAlt,
      floatingCardTitleEn: en.home.hero.floatingCard.title,
      floatingCardTitleAr: ar.home.hero.floatingCard.title,
      floatingCardDescriptionEn: en.home.hero.floatingCard.description,
      floatingCardDescriptionAr: ar.home.hero.floatingCard.description,
      aboutTitleEn: en.home.about.title,
      aboutTitleAr: ar.home.about.title,
      aboutDescriptionEn: en.home.about.description,
      aboutDescriptionAr: ar.home.about.description,
      missionTitleEn: en.home.missionCards[0].title,
      missionTitleAr: ar.home.missionCards[0].title,
      missionDescriptionEn: en.home.missionCards[0].description,
      missionDescriptionAr: ar.home.missionCards[0].description,
      visionTitleEn: en.home.missionCards[1].title,
      visionTitleAr: ar.home.missionCards[1].title,
      visionDescriptionEn: en.home.missionCards[1].description,
      visionDescriptionAr: ar.home.missionCards[1].description,
      valuesTitleEn: en.home.missionCards[2].title,
      valuesTitleAr: ar.home.missionCards[2].title,
      valuesDescriptionEn: en.home.missionCards[2].description,
      valuesDescriptionAr: ar.home.missionCards[2].description,
      coreValuesTitleEn: en.home.coreValues.title,
      coreValuesTitleAr: ar.home.coreValues.title,
      coreValuesDescriptionEn: en.home.coreValues.description,
      coreValuesDescriptionAr: ar.home.coreValues.description,
      coreValuesItemsEn: serializeList(en.home.coreValues.items),
      coreValuesItemsAr: serializeList(ar.home.coreValues.items),
      howItWorksTitleEn: en.home.howItWorks.title,
      howItWorksTitleAr: ar.home.howItWorks.title,
      howItWorksDescriptionEn: en.home.howItWorks.description,
      howItWorksDescriptionAr: ar.home.howItWorks.description,
      stepOneTitleEn: en.home.howItWorks.steps[0].title,
      stepOneTitleAr: ar.home.howItWorks.steps[0].title,
      stepOneDescriptionEn: en.home.howItWorks.steps[0].description,
      stepOneDescriptionAr: ar.home.howItWorks.steps[0].description,
      stepTwoTitleEn: en.home.howItWorks.steps[1].title,
      stepTwoTitleAr: ar.home.howItWorks.steps[1].title,
      stepTwoDescriptionEn: en.home.howItWorks.steps[1].description,
      stepTwoDescriptionAr: ar.home.howItWorks.steps[1].description,
      stepThreeTitleEn: en.home.howItWorks.steps[2].title,
      stepThreeTitleAr: ar.home.howItWorks.steps[2].title,
      stepThreeDescriptionEn: en.home.howItWorks.steps[2].description,
      stepThreeDescriptionAr: ar.home.howItWorks.steps[2].description,
      programsTitleEn: en.home.programs.title,
      programsTitleAr: ar.home.programs.title,
      programsDescriptionEn: en.home.programs.description,
      programsDescriptionAr: ar.home.programs.description,
      libraryServicesTitleEn: en.home.libraryServices.title,
      libraryServicesTitleAr: ar.home.libraryServices.title,
      libraryServicesDescriptionEn: en.home.libraryServices.description,
      libraryServicesDescriptionAr: ar.home.libraryServices.description,
      libraryServicesItemsEn: serializeList(en.home.libraryServices.items),
      libraryServicesItemsAr: serializeList(ar.home.libraryServices.items),
      projectsTitleEn: en.home.projects.title,
      projectsTitleAr: ar.home.projects.title,
      projectsDescriptionEn: en.home.projects.description,
      projectsDescriptionAr: ar.home.projects.description,
      eventsTitleEn: en.home.events.title,
      eventsTitleAr: ar.home.events.title,
      eventsDescriptionEn: en.home.events.description,
      eventsDescriptionAr: ar.home.events.description,
      strategicGoalsTitleEn: en.home.strategicGoals.title,
      strategicGoalsTitleAr: ar.home.strategicGoals.title,
      strategicGoalsDescriptionEn: en.home.strategicGoals.description,
      strategicGoalsDescriptionAr: ar.home.strategicGoals.description,
      strategicGoalsItemsEn: serializeGoals(en.home.strategicGoals.items),
      strategicGoalsItemsAr: serializeGoals(ar.home.strategicGoals.items),
      busFeaturesTitleEn: en.home.busFeatures.title,
      busFeaturesTitleAr: ar.home.busFeatures.title,
      busFeaturesDescriptionEn: en.home.busFeatures.description,
      busFeaturesDescriptionAr: ar.home.busFeatures.description,
      busFeaturesItemsEn: serializeList(en.home.busFeatures.items),
      busFeaturesItemsAr: serializeList(ar.home.busFeatures.items),
      targetAudienceTitleEn: en.home.targetAudience.title,
      targetAudienceTitleAr: ar.home.targetAudience.title,
      targetAudienceDescriptionEn: en.home.targetAudience.description,
      targetAudienceDescriptionAr: ar.home.targetAudience.description,
      targetAudienceItemsEn: serializeList(en.home.targetAudience.items),
      targetAudienceItemsAr: serializeList(ar.home.targetAudience.items),
      operationsTitleEn: en.home.operations.title,
      operationsTitleAr: ar.home.operations.title,
      operationsDescriptionEn: en.home.operations.description,
      operationsDescriptionAr: ar.home.operations.description,
      operationsItemsEn: serializeList(en.home.operations.items),
      operationsItemsAr: serializeList(ar.home.operations.items),
      partnershipsTitleEn: en.home.partnerships.title,
      partnershipsTitleAr: ar.home.partnerships.title,
      partnershipsDescriptionEn: en.home.partnerships.description,
      partnershipsDescriptionAr: ar.home.partnerships.description,
      partnershipsItemsEn: serializeList(en.home.partnerships.items),
      partnershipsItemsAr: serializeList(ar.home.partnerships.items),
      finalMessageTitleEn: en.home.finalMessage.title,
      finalMessageTitleAr: ar.home.finalMessage.title,
      finalMessageDescriptionEn: en.home.finalMessage.description,
      finalMessageDescriptionAr: ar.home.finalMessage.description,
      impactTitleEn: en.home.impact.title,
      impactTitleAr: ar.home.impact.title,
      impactDescriptionEn: en.home.impact.description,
      impactDescriptionAr: ar.home.impact.description,
      statOneLabelEn: en.home.impact.stats[0].label,
      statOneLabelAr: ar.home.impact.stats[0].label,
      statOneValue: en.home.impact.stats[0].value,
      statTwoLabelEn: en.home.impact.stats[1].label,
      statTwoLabelAr: ar.home.impact.stats[1].label,
      statTwoValue: en.home.impact.stats[1].value,
      statThreeLabelEn: en.home.impact.stats[2].label,
      statThreeLabelAr: ar.home.impact.stats[2].label,
      statThreeValue: en.home.impact.stats[2].value,
      statFourLabelEn: en.home.impact.stats[3].label,
      statFourLabelAr: ar.home.impact.stats[3].label,
      statFourValue: en.home.impact.stats[3].value,
      donationCtaTitleEn: en.home.donateCta.title,
      donationCtaTitleAr: ar.home.donateCta.title,
      donationCtaDescriptionEn: en.home.donateCta.description,
      donationCtaDescriptionAr: ar.home.donateCta.description,
      donationCtaButtonLabelEn: en.home.donateCta.button,
      donationCtaButtonLabelAr: ar.home.donateCta.button,
    },
  });

  const pageEntries = Object.entries(en.pages);
  for (const [key, value] of pageEntries) {
    await db.pageContent.upsert({
      where: { key },
      update: {},
      create: {
        key,
        titleEn: value.title,
        titleAr: ar.pages[key as keyof typeof ar.pages].title,
        descriptionEn: value.description,
        descriptionAr: ar.pages[key as keyof typeof ar.pages].description,
      },
    });
  }

  await db.donationSettings.upsert({
    where: { id: "donation-settings" },
    update: {},
    create: {
      id: "donation-settings",
      headingEn: en.donation.heading,
      headingAr: ar.donation.heading,
      descriptionEn: en.donation.description,
      descriptionAr: ar.donation.description,
      bankTransferTabEn: en.donation.tabs.bankTransfer,
      bankTransferTabAr: ar.donation.tabs.bankTransfer,
      onlineSoonTabEn: en.donation.tabs.onlineSoon,
      onlineSoonTabAr: ar.donation.tabs.onlineSoon,
      bankTransferTitleEn: en.donation.bankTransfer.title,
      bankTransferTitleAr: ar.donation.bankTransfer.title,
      bankTransferHelperEn: en.donation.bankTransfer.helper,
      bankTransferHelperAr: ar.donation.bankTransfer.helper,
      bankNameLabelEn: en.donation.bankTransfer.fields[0].label,
      bankNameLabelAr: ar.donation.bankTransfer.fields[0].label,
      bankNameValue: en.donation.bankTransfer.fields[0].value,
      accountNameLabelEn: en.donation.bankTransfer.fields[1].label,
      accountNameLabelAr: ar.donation.bankTransfer.fields[1].label,
      accountNameValue: en.donation.bankTransfer.fields[1].value,
      accountNumberLabelEn: en.donation.bankTransfer.fields[2].label,
      accountNumberLabelAr: ar.donation.bankTransfer.fields[2].label,
      accountNumberValue: en.donation.bankTransfer.fields[2].value,
      ibanLabelEn: en.donation.bankTransfer.fields[3].label,
      ibanLabelAr: ar.donation.bankTransfer.fields[3].label,
      ibanValue: en.donation.bankTransfer.fields[3].value,
      referenceNoteEn: en.donation.bankTransfer.referenceNote,
      referenceNoteAr: ar.donation.bankTransfer.referenceNote,
      formTitleEn: en.donation.form.title,
      formTitleAr: ar.donation.form.title,
      formDescriptionEn: en.donation.form.description,
      formDescriptionAr: ar.donation.form.description,
      formNameLabelEn: en.donation.form.name,
      formNameLabelAr: ar.donation.form.name,
      formEmailLabelEn: en.donation.form.email,
      formEmailLabelAr: ar.donation.form.email,
      formAmountLabelEn: en.donation.form.amount,
      formAmountLabelAr: ar.donation.form.amount,
      formNoteLabelEn: en.donation.form.note,
      formNoteLabelAr: ar.donation.form.note,
      formTransferDateLabelEn: en.donation.form.transferDate,
      formTransferDateLabelAr: ar.donation.form.transferDate,
      formSubmitLabelEn: en.donation.form.submit,
      formSubmitLabelAr: ar.donation.form.submit,
      placeholderTitleEn: en.donation.placeholderCard.title,
      placeholderTitleAr: ar.donation.placeholderCard.title,
      placeholderDescriptionEn: en.donation.placeholderCard.description,
      placeholderDescriptionAr: ar.donation.placeholderCard.description,
      ctaTitleEn: en.donation.cta.title,
      ctaTitleAr: ar.donation.cta.title,
      ctaButtonLabelEn: en.donation.cta.button,
      ctaButtonLabelAr: ar.donation.cta.button,
    },
  });

  await db.contactSettings.upsert({
    where: { id: "contact-settings" },
    update: {},
    create: {
      id: "contact-settings",
      titleEn: en.contact.title,
      titleAr: ar.contact.title,
      descriptionEn: en.contact.description,
      descriptionAr: ar.contact.description,
      emailLabelEn: en.contact.details[0].label,
      emailLabelAr: ar.contact.details[0].label,
      emailValue: en.contact.details[0].value,
      phoneLabelEn: en.contact.details[1].label,
      phoneLabelAr: ar.contact.details[1].label,
      phoneValue: en.contact.details[1].value,
      addressLabelEn: en.contact.details[2].label,
      addressLabelAr: ar.contact.details[2].label,
      addressValueEn: en.contact.details[2].value,
      addressValueAr: ar.contact.details[2].value,
      formNameLabelEn: en.contact.form.name,
      formNameLabelAr: ar.contact.form.name,
      formEmailLabelEn: en.contact.form.email,
      formEmailLabelAr: ar.contact.form.email,
      formSubjectLabelEn: en.contact.form.subject,
      formSubjectLabelAr: ar.contact.form.subject,
      formMessageLabelEn: en.contact.form.message,
      formMessageLabelAr: ar.contact.form.message,
      formSubmitLabelEn: en.contact.form.submit,
      formSubmitLabelAr: ar.contact.form.submit,
    },
  });

  await db.program.deleteMany();
  await db.project.deleteMany();
  await db.event.deleteMany();

  await db.program.createMany({
    data: en.home.programs.items.map((item, index) => ({
      slug: `program-${index + 1}`,
      order: index,
      titleEn: item.title,
      titleAr: ar.home.programs.items[index].title,
      descriptionEn: item.description,
      descriptionAr: ar.home.programs.items[index].description,
      imageUrl: item.image,
      imageAltEn: item.alt,
      imageAltAr: ar.home.programs.items[index].alt,
    })),
  });

  await db.project.createMany({
    data: en.home.projects.items.map((item, index) => ({
      slug: `project-${index + 1}`,
      order: index,
      titleEn: item.title,
      titleAr: ar.home.projects.items[index].title,
      descriptionEn: item.description,
      descriptionAr: ar.home.projects.items[index].description,
      ctaLabelEn: item.cta,
      ctaLabelAr: ar.home.projects.items[index].cta,
      imageUrl: item.image,
      imageAltEn: item.alt,
      imageAltAr: ar.home.projects.items[index].alt,
    })),
  });

  await db.event.createMany({
    data: en.home.events.items.map((item, index) => ({
      slug: `event-${index + 1}`,
      order: index,
      eventDate: new Date(index === 0 ? "2026-05-14" : index === 1 ? "2026-06-02" : "2026-06-19"),
      titleEn: item.title,
      titleAr: ar.home.events.items[index].title,
      descriptionEn: item.description,
      descriptionAr: ar.home.events.items[index].description,
      imageUrl: item.image,
      imageAltEn: item.alt,
      imageAltAr: ar.home.events.items[index].alt,
    })),
  });
}

main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await db.$disconnect();
    process.exit(1);
  });
