-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "public"."AdminUser" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."SiteSettings" (
    "id" TEXT NOT NULL DEFAULT 'site-settings',
    "projectNameEn" TEXT NOT NULL,
    "projectNameAr" TEXT NOT NULL,
    "logoUrl" TEXT,
    "navHomeEn" TEXT NOT NULL,
    "navHomeAr" TEXT NOT NULL,
    "navAboutEn" TEXT NOT NULL,
    "navAboutAr" TEXT NOT NULL,
    "navProgramsEn" TEXT NOT NULL,
    "navProgramsAr" TEXT NOT NULL,
    "navProjectsEn" TEXT NOT NULL,
    "navProjectsAr" TEXT NOT NULL,
    "navEventsEn" TEXT NOT NULL,
    "navEventsAr" TEXT NOT NULL,
    "navDonateEn" TEXT NOT NULL,
    "navDonateAr" TEXT NOT NULL,
    "navContactEn" TEXT NOT NULL,
    "navContactAr" TEXT NOT NULL,
    "footerDescriptionEn" TEXT NOT NULL,
    "footerDescriptionAr" TEXT NOT NULL,
    "footerContactLabelEn" TEXT NOT NULL,
    "footerContactLabelAr" TEXT NOT NULL,
    "footerSocialLabelEn" TEXT NOT NULL,
    "footerSocialLabelAr" TEXT NOT NULL,
    "footerDonateLabelEn" TEXT NOT NULL,
    "footerDonateLabelAr" TEXT NOT NULL,
    "footerRightsEn" TEXT NOT NULL,
    "footerRightsAr" TEXT NOT NULL,
    "socialOneLabelEn" TEXT NOT NULL,
    "socialOneLabelAr" TEXT NOT NULL,
    "socialOneUrl" TEXT NOT NULL,
    "socialTwoLabelEn" TEXT NOT NULL,
    "socialTwoLabelAr" TEXT NOT NULL,
    "socialTwoUrl" TEXT NOT NULL,
    "socialThreeLabelEn" TEXT NOT NULL,
    "socialThreeLabelAr" TEXT NOT NULL,
    "socialThreeUrl" TEXT NOT NULL,
    "seoTitleEn" TEXT,
    "seoTitleAr" TEXT,
    "seoDescriptionEn" TEXT,
    "seoDescriptionAr" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."HomePage" (
    "id" TEXT NOT NULL DEFAULT 'home-page',
    "heroEyebrowEn" TEXT NOT NULL,
    "heroEyebrowAr" TEXT NOT NULL,
    "heroTitleEn" TEXT NOT NULL,
    "heroTitleAr" TEXT NOT NULL,
    "heroDescriptionEn" TEXT NOT NULL,
    "heroDescriptionAr" TEXT NOT NULL,
    "heroPrimaryActionEn" TEXT NOT NULL,
    "heroPrimaryActionAr" TEXT NOT NULL,
    "heroSecondaryActionEn" TEXT NOT NULL,
    "heroSecondaryActionAr" TEXT NOT NULL,
    "heroImageUrl" TEXT,
    "heroImageAltEn" TEXT NOT NULL,
    "heroImageAltAr" TEXT NOT NULL,
    "floatingCardTitleEn" TEXT NOT NULL,
    "floatingCardTitleAr" TEXT NOT NULL,
    "floatingCardDescriptionEn" TEXT NOT NULL,
    "floatingCardDescriptionAr" TEXT NOT NULL,
    "aboutTitleEn" TEXT NOT NULL,
    "aboutTitleAr" TEXT NOT NULL,
    "aboutDescriptionEn" TEXT NOT NULL,
    "aboutDescriptionAr" TEXT NOT NULL,
    "missionTitleEn" TEXT NOT NULL,
    "missionTitleAr" TEXT NOT NULL,
    "missionDescriptionEn" TEXT NOT NULL,
    "missionDescriptionAr" TEXT NOT NULL,
    "visionTitleEn" TEXT NOT NULL,
    "visionTitleAr" TEXT NOT NULL,
    "visionDescriptionEn" TEXT NOT NULL,
    "visionDescriptionAr" TEXT NOT NULL,
    "valuesTitleEn" TEXT NOT NULL,
    "valuesTitleAr" TEXT NOT NULL,
    "valuesDescriptionEn" TEXT NOT NULL,
    "valuesDescriptionAr" TEXT NOT NULL,
    "coreValuesTitleEn" TEXT NOT NULL,
    "coreValuesTitleAr" TEXT NOT NULL,
    "coreValuesDescriptionEn" TEXT NOT NULL,
    "coreValuesDescriptionAr" TEXT NOT NULL,
    "coreValuesItemsEn" TEXT NOT NULL,
    "coreValuesItemsAr" TEXT NOT NULL,
    "howItWorksTitleEn" TEXT NOT NULL,
    "howItWorksTitleAr" TEXT NOT NULL,
    "howItWorksDescriptionEn" TEXT NOT NULL,
    "howItWorksDescriptionAr" TEXT NOT NULL,
    "stepOneTitleEn" TEXT NOT NULL,
    "stepOneTitleAr" TEXT NOT NULL,
    "stepOneDescriptionEn" TEXT NOT NULL,
    "stepOneDescriptionAr" TEXT NOT NULL,
    "stepTwoTitleEn" TEXT NOT NULL,
    "stepTwoTitleAr" TEXT NOT NULL,
    "stepTwoDescriptionEn" TEXT NOT NULL,
    "stepTwoDescriptionAr" TEXT NOT NULL,
    "stepThreeTitleEn" TEXT NOT NULL,
    "stepThreeTitleAr" TEXT NOT NULL,
    "stepThreeDescriptionEn" TEXT NOT NULL,
    "stepThreeDescriptionAr" TEXT NOT NULL,
    "programsTitleEn" TEXT NOT NULL,
    "programsTitleAr" TEXT NOT NULL,
    "programsDescriptionEn" TEXT NOT NULL,
    "programsDescriptionAr" TEXT NOT NULL,
    "libraryServicesTitleEn" TEXT NOT NULL,
    "libraryServicesTitleAr" TEXT NOT NULL,
    "libraryServicesDescriptionEn" TEXT NOT NULL,
    "libraryServicesDescriptionAr" TEXT NOT NULL,
    "libraryServicesItemsEn" TEXT NOT NULL,
    "libraryServicesItemsAr" TEXT NOT NULL,
    "projectsTitleEn" TEXT NOT NULL,
    "projectsTitleAr" TEXT NOT NULL,
    "projectsDescriptionEn" TEXT NOT NULL,
    "projectsDescriptionAr" TEXT NOT NULL,
    "eventsTitleEn" TEXT NOT NULL,
    "eventsTitleAr" TEXT NOT NULL,
    "eventsDescriptionEn" TEXT NOT NULL,
    "eventsDescriptionAr" TEXT NOT NULL,
    "strategicGoalsTitleEn" TEXT NOT NULL,
    "strategicGoalsTitleAr" TEXT NOT NULL,
    "strategicGoalsDescriptionEn" TEXT NOT NULL,
    "strategicGoalsDescriptionAr" TEXT NOT NULL,
    "strategicGoalsItemsEn" TEXT NOT NULL,
    "strategicGoalsItemsAr" TEXT NOT NULL,
    "busFeaturesTitleEn" TEXT NOT NULL,
    "busFeaturesTitleAr" TEXT NOT NULL,
    "busFeaturesDescriptionEn" TEXT NOT NULL,
    "busFeaturesDescriptionAr" TEXT NOT NULL,
    "busFeaturesItemsEn" TEXT NOT NULL,
    "busFeaturesItemsAr" TEXT NOT NULL,
    "targetAudienceTitleEn" TEXT NOT NULL,
    "targetAudienceTitleAr" TEXT NOT NULL,
    "targetAudienceDescriptionEn" TEXT NOT NULL,
    "targetAudienceDescriptionAr" TEXT NOT NULL,
    "targetAudienceItemsEn" TEXT NOT NULL,
    "targetAudienceItemsAr" TEXT NOT NULL,
    "operationsTitleEn" TEXT NOT NULL,
    "operationsTitleAr" TEXT NOT NULL,
    "operationsDescriptionEn" TEXT NOT NULL,
    "operationsDescriptionAr" TEXT NOT NULL,
    "operationsItemsEn" TEXT NOT NULL,
    "operationsItemsAr" TEXT NOT NULL,
    "partnershipsTitleEn" TEXT NOT NULL,
    "partnershipsTitleAr" TEXT NOT NULL,
    "partnershipsDescriptionEn" TEXT NOT NULL,
    "partnershipsDescriptionAr" TEXT NOT NULL,
    "partnershipsItemsEn" TEXT NOT NULL,
    "partnershipsItemsAr" TEXT NOT NULL,
    "finalMessageTitleEn" TEXT NOT NULL,
    "finalMessageTitleAr" TEXT NOT NULL,
    "finalMessageDescriptionEn" TEXT NOT NULL,
    "finalMessageDescriptionAr" TEXT NOT NULL,
    "impactTitleEn" TEXT NOT NULL,
    "impactTitleAr" TEXT NOT NULL,
    "impactDescriptionEn" TEXT NOT NULL,
    "impactDescriptionAr" TEXT NOT NULL,
    "statOneLabelEn" TEXT NOT NULL,
    "statOneLabelAr" TEXT NOT NULL,
    "statOneValue" TEXT NOT NULL,
    "statTwoLabelEn" TEXT NOT NULL,
    "statTwoLabelAr" TEXT NOT NULL,
    "statTwoValue" TEXT NOT NULL,
    "statThreeLabelEn" TEXT NOT NULL,
    "statThreeLabelAr" TEXT NOT NULL,
    "statThreeValue" TEXT NOT NULL,
    "statFourLabelEn" TEXT NOT NULL,
    "statFourLabelAr" TEXT NOT NULL,
    "statFourValue" TEXT NOT NULL,
    "donationCtaTitleEn" TEXT NOT NULL,
    "donationCtaTitleAr" TEXT NOT NULL,
    "donationCtaDescriptionEn" TEXT NOT NULL,
    "donationCtaDescriptionAr" TEXT NOT NULL,
    "donationCtaButtonLabelEn" TEXT NOT NULL,
    "donationCtaButtonLabelAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HomePage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PageContent" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "titleEn" TEXT NOT NULL,
    "titleAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PageContent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Program" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "titleEn" TEXT NOT NULL,
    "titleAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "imageUrl" TEXT,
    "imageAltEn" TEXT NOT NULL,
    "imageAltAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Program_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Project" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "titleEn" TEXT NOT NULL,
    "titleAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "ctaLabelEn" TEXT NOT NULL,
    "ctaLabelAr" TEXT NOT NULL,
    "imageUrl" TEXT,
    "imageAltEn" TEXT NOT NULL,
    "imageAltAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Event" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "eventDate" TIMESTAMP(3) NOT NULL,
    "titleEn" TEXT NOT NULL,
    "titleAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "imageUrl" TEXT,
    "imageAltEn" TEXT NOT NULL,
    "imageAltAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."DonationSettings" (
    "id" TEXT NOT NULL DEFAULT 'donation-settings',
    "headingEn" TEXT NOT NULL,
    "headingAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "bankTransferTabEn" TEXT NOT NULL,
    "bankTransferTabAr" TEXT NOT NULL,
    "onlineSoonTabEn" TEXT NOT NULL,
    "onlineSoonTabAr" TEXT NOT NULL,
    "bankTransferTitleEn" TEXT NOT NULL,
    "bankTransferTitleAr" TEXT NOT NULL,
    "bankTransferHelperEn" TEXT NOT NULL,
    "bankTransferHelperAr" TEXT NOT NULL,
    "bankNameLabelEn" TEXT NOT NULL,
    "bankNameLabelAr" TEXT NOT NULL,
    "bankNameValue" TEXT NOT NULL,
    "accountNameLabelEn" TEXT NOT NULL,
    "accountNameLabelAr" TEXT NOT NULL,
    "accountNameValue" TEXT NOT NULL,
    "accountNumberLabelEn" TEXT NOT NULL,
    "accountNumberLabelAr" TEXT NOT NULL,
    "accountNumberValue" TEXT NOT NULL,
    "ibanLabelEn" TEXT NOT NULL,
    "ibanLabelAr" TEXT NOT NULL,
    "ibanValue" TEXT NOT NULL,
    "referenceNoteEn" TEXT NOT NULL,
    "referenceNoteAr" TEXT NOT NULL,
    "formTitleEn" TEXT NOT NULL,
    "formTitleAr" TEXT NOT NULL,
    "formDescriptionEn" TEXT NOT NULL,
    "formDescriptionAr" TEXT NOT NULL,
    "formNameLabelEn" TEXT NOT NULL,
    "formNameLabelAr" TEXT NOT NULL,
    "formEmailLabelEn" TEXT NOT NULL,
    "formEmailLabelAr" TEXT NOT NULL,
    "formAmountLabelEn" TEXT NOT NULL,
    "formAmountLabelAr" TEXT NOT NULL,
    "formNoteLabelEn" TEXT NOT NULL,
    "formNoteLabelAr" TEXT NOT NULL,
    "formTransferDateLabelEn" TEXT NOT NULL,
    "formTransferDateLabelAr" TEXT NOT NULL,
    "formSubmitLabelEn" TEXT NOT NULL,
    "formSubmitLabelAr" TEXT NOT NULL,
    "placeholderTitleEn" TEXT NOT NULL,
    "placeholderTitleAr" TEXT NOT NULL,
    "placeholderDescriptionEn" TEXT NOT NULL,
    "placeholderDescriptionAr" TEXT NOT NULL,
    "ctaTitleEn" TEXT NOT NULL,
    "ctaTitleAr" TEXT NOT NULL,
    "ctaButtonLabelEn" TEXT NOT NULL,
    "ctaButtonLabelAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DonationSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ContactSettings" (
    "id" TEXT NOT NULL DEFAULT 'contact-settings',
    "titleEn" TEXT NOT NULL,
    "titleAr" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionAr" TEXT NOT NULL,
    "emailLabelEn" TEXT NOT NULL,
    "emailLabelAr" TEXT NOT NULL,
    "emailValue" TEXT NOT NULL,
    "phoneLabelEn" TEXT NOT NULL,
    "phoneLabelAr" TEXT NOT NULL,
    "phoneValue" TEXT NOT NULL,
    "addressLabelEn" TEXT NOT NULL,
    "addressLabelAr" TEXT NOT NULL,
    "addressValueEn" TEXT NOT NULL,
    "addressValueAr" TEXT NOT NULL,
    "formNameLabelEn" TEXT NOT NULL,
    "formNameLabelAr" TEXT NOT NULL,
    "formEmailLabelEn" TEXT NOT NULL,
    "formEmailLabelAr" TEXT NOT NULL,
    "formSubjectLabelEn" TEXT NOT NULL,
    "formSubjectLabelAr" TEXT NOT NULL,
    "formMessageLabelEn" TEXT NOT NULL,
    "formMessageLabelAr" TEXT NOT NULL,
    "formSubmitLabelEn" TEXT NOT NULL,
    "formSubmitLabelAr" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ContactSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AdminUser_email_key" ON "public"."AdminUser"("email");

-- CreateIndex
CREATE UNIQUE INDEX "PageContent_key_key" ON "public"."PageContent"("key");

-- CreateIndex
CREATE UNIQUE INDEX "Program_slug_key" ON "public"."Program"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Project_slug_key" ON "public"."Project"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Event_slug_key" ON "public"."Event"("slug");
